# Generated by Django 4.0.3 on 2022-04-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='verifiedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
