# Generated by Django 4.0.3 on 2022-06-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CeylonuniApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityEmail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=150, unique=True)),
            ],
        ),
    ]
