# Generated by Django 4.0.3 on 2022-04-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CeylonuniApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(max_length=350, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='deletedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='universities',
            name='createdAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='universities',
            name='updatedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
