# Generated by Django 4.0.3 on 2022-04-03 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CeylonuniApp', '0002_alter_accounts_createdat_alter_accounts_deletedat_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accounts',
        ),
    ]
